# Generated by Django 5.2.12 on 2026-03-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('phone', models.CharField(max_length=15)),
                ('store_type', models.CharField(default='Gift Shop', max_length=100)),
            ],
        ),
    ]
