# Generated by Django 5.2.12 on 2026-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='revenue',
            field=models.IntegerField(default=0, verbose_name='Doanh thu (VNĐ)'),
        ),
    ]
