# Generated by Django 5.2.12 on 2026-04-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
