# Generated by Django 5.2.12 on 2026-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ giao hàng'),
        ),
    ]
